version: "2"
services:
  ixo-web:
    build: .
    environment:
      - REACT_APP_BLOCKCHAIN_NODE_URL=http://beta.cosmos.ixo.world:46657
      - REACT_APP_BLOCK_SYNC_URL=http://beta.cosmos.ixo.world:8080
 



