version: "2"
services:
  ixo-web:
    container_name: ixo-web
    image: trustlab/ixo-web:latest
    environment:
      - PORT=80
    ports:
      - "80:80"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
 