[template]

[template.environment]
  NODE_PATH = "src"
  REACT_APP_ASSISTANT_URL = "-"
  REACT_APP_CHAIN_ID = ""
  REACT_APP_CONFIG_EXCHANGE_URL = ""
  REACT_APP_CONFIG_RELAYER_URL = ""
  REACT_APP_CONFIG_SCHEMA_URL = ""
  REACT_APP_EMBEDLY_KEY = "-"
  REACT_APP_ENTITY_PAGE_VERSION = ""
  REACT_APP_ENTITY_VERSION = ""
  REACT_APP_GAIA_URL = ""
  REACT_APP_GOOGLE_API_KEY = "-"
  REACT_APP_INTERCOM_APP_ID = ""
  REACT_APP_INTERCOM_ENABLED = ""
  REACT_APP_IXO_TOKEN_CONTRACT_ADDRESS = ""
  REACT_APP_IXO_WORLD_ORIGIN = ""
  REACT_APP_KYC_LINK = ""
  REACT_APP_NAME = ""
  REACT_APP_PDS_URL = ""
  REACT_APP_PROJECT_REGISTRY_CONTRACT_ADDRESS = ""
  REACT_APP_RELAYER_NODE = ""
#ixo-networks/networkconfig

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"